version: '3'

services:
  idontknow.rest:
    image: idontknow.rest
    build:
      context: ./backend/Idontknow.Api
      dockerfile: Dockerfile
  idontknow.web:
    image: idontknow.web
    build:
      context: ./frontend/Idontknow.web
      dockerfile: Dockerfile
  idontknow.web.ts:
    image: idontknow.web.ts
    build:
      context: ./frontend/Idontknow.web.ts
      dockerfile: Dockerfile